extends SceneTree

const TestAssertHelper := preload("res://tests/support/test_assert.gd")
const VehicleProfileTests := preload("res://tests/preview/test_vehicle_profiles.gd")
const PreviewGameScaleTests := preload("res://tests/preview/test_preview_game_scale.gd")
const PreviewFoundationTests := preload("res://tests/preview/test_preview_foundation.gd")
const AnchorPreviewInteractionTests := preload("res://tests/preview/test_anchor_preview_interaction.gd")
const EditorPreviewIntegrationTests := preload("res://tests/preview/test_editor_preview_integration.gd")
const PreviewStabilizationTests := preload("res://tests/preview/test_preview_stabilization.gd")
const PreviewRenderPlanTests := preload("res://tests/preview/test_preview_render_plan.gd")
const StaticLayerRendererTests := preload("res://tests/preview/test_static_layer_renderers.gd")
const DynamicLayerRendererTests := preload("res://tests/preview/test_dynamic_layer_renderers.gd")
const ParticleDirectionSemanticsTests := preload("res://tests/preview/test_particle_direction_semantics.gd")
const PreviewPlaybackTests := preload("res://tests/preview/test_preview_playback.gd")
const PreviewStaleStateTests := preload("res://tests/preview/test_preview_stale_state.gd")
const RendererShowcaseTests := preload("res://tests/preview/test_renderer_showcase.gd")
const ZeroZoneVisibilityDiagnosticTests := preload("res://tests/preview/test_zero_zone_visibility_diagnostic.gd")
const TexturedParticleAssetTests := preload("res://tests/preview/test_textured_particle_assets.gd")
const StandardBoosterAuthoringTests := preload("res://tests/preview/test_standard_booster_authoring.gd")
const HighSpeedWindAuthoringTests := preload("res://tests/preview/test_high_speed_wind_authoring.gd")
const RainTireSprayAuthoringTests := preload("res://tests/preview/test_rain_tire_spray_authoring.gd")
const SnowTireSprayAuthoringTests := preload("res://tests/preview/test_snow_tire_spray_authoring.gd")
const TexturedSpriteLayerRendererTests := preload("res://tests/preview/test_textured_sprite_layer_renderer.gd")
const HeadlightAuthoringTests := preload("res://tests/preview/test_headlight_authoring.gd")
const SuperBoosterAuthoringTests := preload("res://tests/preview/test_super_booster_authoring.gd")
const SuperBoosterDualAuthoringTests := preload("res://tests/preview/test_super_booster_dual_authoring.gd")
const RotorLiftDownwashAuthoringTests := preload("res://tests/preview/test_rotor_lift_downwash_authoring.gd")
const RuntimeModulationProgramTests := preload("res://tests/preview/test_runtime_modulation_program.gd")


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	var tests := TestAssertHelper.new()
	VehicleProfileTests.run(tests)
	PreviewGameScaleTests.run(tests)
	PreviewFoundationTests.run(tests)
	AnchorPreviewInteractionTests.run(tests)
	EditorPreviewIntegrationTests.run(tests)
	PreviewStabilizationTests.run(tests)
	PreviewRenderPlanTests.run(tests)
	StaticLayerRendererTests.run(tests)
	DynamicLayerRendererTests.run(tests)
	ParticleDirectionSemanticsTests.run(tests)
	PreviewPlaybackTests.run(tests)
	PreviewStaleStateTests.run(tests)
	RendererShowcaseTests.run(tests)
	ZeroZoneVisibilityDiagnosticTests.run(tests)
	TexturedParticleAssetTests.run(tests)
	StandardBoosterAuthoringTests.run(tests)
	HighSpeedWindAuthoringTests.run(tests)
	preload("res://tests/preview/test_downforce_wing_authoring.gd").run(tests)
	RainTireSprayAuthoringTests.run(tests)
	SnowTireSprayAuthoringTests.run(tests)
	TexturedSpriteLayerRendererTests.run(tests)
	HeadlightAuthoringTests.run(tests)
	SuperBoosterAuthoringTests.run(tests)
	SuperBoosterDualAuthoringTests.run(tests)
	RotorLiftDownwashAuthoringTests.run(tests)
	RuntimeModulationProgramTests.run(tests)
	print("PREVIEW_TEST_ASSERTIONS=%d FAILURES=%d" % [tests.assertion_count(), tests.failure_count()])
	quit(1 if tests.failure_count() > 0 else 0)
