extends RefCounted

const VfxPresetPipelineModel := preload("res://src/app/vfx_preset_pipeline.gd")
const VfxPresetCodecModel := preload("res://src/model/vfx_preset_codec.gd")
const VfxRuleCatalogModel := preload("res://src/model/vfx_rule_catalog.gd")
const VfxSchemaRegistryModel := preload("res://src/model/vfx_schema_registry.gd")
const VfxPreviewAssetRegistryModel := preload("res://src/preview/rendering/vfx_preview_asset_registry.gd")
const VfxPreviewAssetResolverModel := preload("res://src/preview/rendering/vfx_preview_asset_resolver.gd")
const VfxPreviewRenderPlanBuilderModel := preload("res://src/preview/rendering/vfx_preview_render_plan_builder.gd")
const VfxPreviewRenderRuntimeModel := preload("res://src/preview/rendering/vfx_preview_render_runtime.gd")
const VfxPreviewRendererFactoryModel := preload("res://src/preview/rendering/vfx_preview_renderer_factory.gd")
const VfxPreviewRuntimeInputStateModel := preload("res://src/preview/runtime_modulation/vfx_preview_runtime_input_state.gd")
const VfxPreviewLodFilterModel := preload("res://src/performance/vfx_preview_lod_filter.gd")
const VfxPerformancePolicyModel := preload("res://src/performance/vfx_performance_policy.gd")

# Headlights v2 (2026-10-09). Textures are generated by tools/headlight_texture_generator.gd; the beam axis points up
# and the root sits near the bottom centre. The root lands on the lamp pair at source px (+-44, -176).
const LEFT_ROOT := Vector2(-44.0, -176.0)
const RIGHT_ROOT := Vector2(44.0, -176.0)
const GAME_SCALE := 0.095
const CORE_SIZE := Vector2i(160, 256)
const SOFT_SIZE := Vector2i(256, 240)
const CORE_ROOT_TEXEL := Vector2(79.5, 248.0)
const SOFT_ROOT_TEXEL := Vector2(127.5, 232.0)
const CORE_SCALE := 2.0
const SOFT_SCALE := 2.4
const CORE_ROTATION := 3.0
const SOFT_ROTATION := 4.0
const LOOP_OPACITY := {"soft": 0.9, "core": 0.40}
const END_OPACITY_RATIO := 0.5
const START_SECONDS := 0.18
const LOOP_IDS := ["loop.left_soft_beam", "loop.right_soft_beam", "loop.left_core_beam", "loop.right_core_beam"]
const START_IDS := ["start.left_soft_beam", "start.right_soft_beam", "start.left_core_beam", "start.right_core_beam"]
const END_IDS := ["end.left_soft_beam", "end.right_soft_beam", "end.left_core_beam", "end.right_core_beam"]


static func run(tests: TestAssert) -> void:
	_test_headlight_assets_and_static_phase_contract(tests)
	_test_headlight_roots_and_game_footprints(tests)
	_test_headlight_runtime_modulation_authoring(tests)
	_test_headlight_runtime_modulation_preview_behavior(tests)


static func _test_headlight_assets_and_static_phase_contract(tests: TestAssert) -> void:
	var assets := _resolved_assets()
	var core_image: Image = assets.get("core", {}).get("texture").get_image() if assets.get("core", {}).get("texture") is Texture2D else null
	var soft_image: Image = assets.get("soft", {}).get("texture").get_image() if assets.get("soft", {}).get("texture") is Texture2D else null
	var document_result: VfxResult = VfxPresetPipelineModel.new().load_and_validate("res://presets/examples/driving.headlights.vfx.json")
	if not document_result.success:
		tests.expect_true(false, "Headlight static authoring requires a valid driving.headlights Preset")
		return
	var data: Dictionary = document_result.value.normalized_data
	var phases: Dictionary = data.get("phases", {})
	var start_layers: Array = phases.get("start", {}).get("layers", [])
	var loop_layers: Array = phases.get("loop", {}).get("layers", [])
	var end_layers: Array = phases.get("end", {}).get("layers", [])
	var loop := _layers_by_id(loop_layers)
	var phase_shapes_match := _layer_ids(start_layers) == START_IDS and _layer_ids(loop_layers) == LOOP_IDS and _layer_ids(end_layers) == END_IDS
	var loop_contract_matches := _matches_beam(loop.get("loop.left_soft_beam", {}), "fx.headlight_beam_soft", "DETAIL", SOFT_SCALE, 360.0 - SOFT_ROTATION, LOOP_OPACITY.soft) \
		and _matches_beam(loop.get("loop.right_soft_beam", {}), "fx.headlight_beam_soft", "DETAIL", SOFT_SCALE, SOFT_ROTATION, LOOP_OPACITY.soft) \
		and _matches_beam(loop.get("loop.left_core_beam", {}), "fx.headlight_beam_core", "CORE", CORE_SCALE, 360.0 - CORE_ROTATION, LOOP_OPACITY.core) \
		and _matches_beam(loop.get("loop.right_core_beam", {}), "fx.headlight_beam_core", "CORE", CORE_SCALE, CORE_ROTATION, LOOP_OPACITY.core)
	var lifecycle_matches := _phase_uses_loop_geometry(start_layers, loop, 1.0) and _phase_uses_loop_geometry(end_layers, loop, END_OPACITY_RATIO)
	tests.expect_true(
		assets.get("core", {}).get("source") == "TEXTURE" and assets.get("soft", {}).get("source") == "TEXTURE" \
		and core_image != null and soft_image != null \
		and core_image.get_size() == CORE_SIZE and soft_image.get_size() == SOFT_SIZE \
		and data.get("preset_id") == "driving.headlights" and data.get("category") == "UTILITY" \
		and data.get("lifecycle", {}).get("mode") == "START_LOOP_END" and data.get("default_space_mode") == "VEHICLE_LOCAL" and data.get("runtime_inputs") == ["speed_normalized", "longitudinal_load"] \
		and phase_shapes_match and loop_contract_matches and lifecycle_matches,
		"Headlight v2 registers the 160x256 core and 256x240 soft RGBA textures in exactly four persistent beams per phase (ADDITIVE core, ALPHA spill) with stable LOOP IDs and no particle authoring"
	)
	tests.expect_true(
		_texture_is_clean_light_cone(core_image, CORE_ROOT_TEXEL, 0.55, 1.0, 40.0, 110.0, true) \
		and _texture_is_clean_light_cone(soft_image, SOFT_ROOT_TEXEL, 0.2, 0.7, 20.0, 110.0, false),
		"Headlight textures keep a transparent border, a centred axis, a hot spot just beyond the vehicle nose (core), and warm-white core versus cool-white spill colour"
	)


static func _test_headlight_roots_and_game_footprints(tests: TestAssert) -> void:
	var document_result: VfxResult = VfxPresetPipelineModel.new().load_and_validate("res://presets/examples/driving.headlights.vfx.json")
	if not document_result.success:
		tests.expect_true(false, "Headlight root and footprint checks require a valid driving.headlights Preset")
		return
	var loop := _layers_by_id(document_result.value.normalized_data.get("phases", {}).get("loop", {}).get("layers", []))
	var left_soft: Dictionary = loop.get("loop.left_soft_beam", {})
	var right_soft: Dictionary = loop.get("loop.right_soft_beam", {})
	var left_core: Dictionary = loop.get("loop.left_core_beam", {})
	var right_core: Dictionary = loop.get("loop.right_core_beam", {})
	var assets := _resolved_assets()
	var core_image: Image = assets.get("core", {}).get("texture").get_image() if assets.get("core", {}).get("texture") is Texture2D else null
	var soft_image: Image = assets.get("soft", {}).get("texture").get_image() if assets.get("soft", {}).get("texture") is Texture2D else null
	var core_footprint := _game_footprint(_visible_bounds(core_image, 0.08), left_core, 1.0)
	var soft_footprint := _game_footprint(_visible_bounds(soft_image, 0.08), left_soft, 1.0)
	var profiles_match := true
	for profile_name in ["formula", "sports", "gt", "hyper"]:
		var profile_result: VfxResult = VfxPresetCodecModel.new().decode_file("res://profiles/vehicles/%s.vehicle_profile.json" % profile_name)
		var anchors: Dictionary = profile_result.value.get("anchors", {}) if profile_result.success else {}
		var front: Vector2 = _anchor(anchors, "FRONT")
		var left_side: Vector2 = _anchor(anchors, "LEFT_SIDE")
		var right_side: Vector2 = _anchor(anchors, "RIGHT_SIDE")
		profiles_match = profiles_match and profile_result.success \
			and LEFT_ROOT.y > front.y and LEFT_ROOT.y < -170.0 \
			and RIGHT_ROOT.y > front.y and RIGHT_ROOT.y < -170.0 \
			and LEFT_ROOT.x > left_side.x and RIGHT_ROOT.x < right_side.x
	tests.expect_true(
		_beam_root_source(left_soft, SOFT_ROOT_TEXEL, SOFT_SIZE).distance_to(LEFT_ROOT) <= 0.001 and _beam_root_source(right_soft, SOFT_ROOT_TEXEL, SOFT_SIZE).distance_to(RIGHT_ROOT) <= 0.001 \
		and _beam_root_source(left_core, CORE_ROOT_TEXEL, CORE_SIZE).distance_to(LEFT_ROOT) <= 0.001 and _beam_root_source(right_core, CORE_ROOT_TEXEL, CORE_SIZE).distance_to(RIGHT_ROOT) <= 0.001 \
		and is_equal_approx(LEFT_ROOT.x, -RIGHT_ROOT.x) and is_equal_approx(LEFT_ROOT.y, RIGHT_ROOT.y) \
		and is_equal_approx(float(left_soft.get("transform", {}).get("rotation_degrees", 0.0)) + float(right_soft.get("transform", {}).get("rotation_degrees", 0.0)), 360.0) \
		and is_equal_approx(float(left_core.get("transform", {}).get("rotation_degrees", 0.0)) + float(right_core.get("transform", {}).get("rotation_degrees", 0.0)), 360.0) \
		and core_footprint.y >= 24.0 and core_footprint.y <= 32.0 and core_footprint.x >= 12.0 and core_footprint.x <= 19.0 \
		and soft_footprint.y >= 27.0 and soft_footprint.y <= 35.0 and soft_footprint.x >= 22.0 and soft_footprint.x <= 31.0 \
		and profiles_match,
		"Headlight soft and core beam roots land on one bilateral front-lamp pair (within 0.001 source px) and their visible footprints stay bounded at Game scale"
	)


static func _test_headlight_runtime_modulation_authoring(tests: TestAssert) -> void:
	var document_result: VfxResult = VfxPresetPipelineModel.new().load_and_validate("res://presets/examples/driving.headlights.vfx.json")
	if not document_result.success:
		tests.expect_true(false, "Headlight Runtime Modulation authoring requires a valid production Preset")
		return
	var data: Dictionary = document_result.value.normalized_data
	var sources: Array = data.get("runtime_modulation_sources", [])
	var source_matches: bool = sources.size() == 2 \
		and sources[0] == {"id": "road.motion", "type": "OSCILLATOR", "wave": "SINE", "frequency_hz": 1.0, "phase_degrees": 0.0} \
		and sources[1].get("id") == "start.ignite" and sources[1].get("type") == "LINEAR_PHASE" \
		and absf(float(sources[1].get("frequency_hz", 0.0)) - 1.0 / START_SECONDS) <= 0.0001
	var all_layers_match := true
	for phase_name in ["start", "loop", "end"]:
		for layer in data.get("phases", {}).get(phase_name, {}).get("layers", []):
			if not layer is Dictionary:
				all_layers_match = false
				continue
			var layer_id := str(layer.get("id", ""))
			var is_soft := layer_id.contains("soft")
			var transform: Dictionary = layer.get("transform", {})
			var expected_pivot: Vector2 = (SOFT_ROOT_TEXEL - Vector2(SOFT_SIZE) * 0.5) if is_soft else (CORE_ROOT_TEXEL - Vector2(CORE_SIZE) * 0.5)
			all_layers_match = all_layers_match and _vector_matches(transform.get("modulation_pivot_local", []), expected_pivot) \
				and _modulation_set_matches(layer.get("modulations", []), phase_name == "start") \
				and _scale_y_clamp_matches(layer.get("modulation_clamps", []), is_soft, phase_name == "start")
	tests.expect_true(
		source_matches and all_layers_match,
		"All twelve Headlight beam Layers declare the shared 1Hz road source, root pivots, speed/load Scale Y, road rotation, speed/load opacity, START-only ignition ramps, and non-contacting Scale Y safety clamps"
	)


static func _test_headlight_runtime_modulation_preview_behavior(tests: TestAssert) -> void:
	var document_result: VfxResult = VfxPresetPipelineModel.new().load_and_validate("res://presets/examples/driving.headlights.vfx.json")
	var plan_result: VfxResult = VfxPreviewRenderPlanBuilderModel.new(_registry()).build(document_result.value.normalized_data) if document_result.success else VfxResult.failure(document_result.issues)
	var policy_result: VfxResult = VfxPerformancePolicyModel.new().load(_registry())
	if not plan_result.success or not policy_result.success:
		tests.expect_true(false, "Headlight Runtime Modulation Preview checks require a compiled Plan and Performance Policy")
		return
	var root_error_max := 0.0
	var normal_sweep_clamp_hits := 0
	var dynamic_matches := true
	for phase_name in ["start", "loop", "end"]:
		for speed in [0.0, 0.25, 0.5, 0.75, 1.0]:
			for load_value in [-1.0, -0.5, 0.0, 0.5, 1.0]:
				for preview_time in [0.0, 0.05, 0.25, 0.75]:
					var sampled_road := sin(TAU * preview_time)
					var ignite := fposmod(preview_time / START_SECONDS, 1.0) if phase_name == "start" else 1.0
					var runtime := _runtime_for(plan_result.value, speed, load_value, preview_time, phase_name)
					if runtime == null:
						dynamic_matches = false
						continue
					var expected_factor: float = (1.0 + 0.05 * speed) * lerpf(0.90, 1.10, (load_value + 1.0) * 0.5) * lerpf(0.99, 1.01, (sampled_road + 1.0) * 0.5) * (lerpf(0.72, 1.0, ignite) if phase_name == "start" else 1.0)
					var expected_opacity_factor: float = (1.0 + 0.05 * speed) * lerpf(1.12, 0.94, (load_value + 1.0) * 0.5) * (lerpf(0.15, 1.0, ignite) if phase_name == "start" else 1.0)
					for packet_value in runtime.draw_packets():
						if not packet_value is Dictionary:
							dynamic_matches = false
							continue
						var packet: Dictionary = packet_value
						var layer_id := str(packet.get("layer_id", ""))
						var is_soft := layer_id.contains("soft")
						var pivot: Vector2 = (SOFT_ROOT_TEXEL - Vector2(SOFT_SIZE) * 0.5) if is_soft else (CORE_ROOT_TEXEL - Vector2(CORE_SIZE) * 0.5)
						var scale: Vector2 = packet.get("geometry_scale", Vector2.ZERO)
						var rotation := float(packet.get("geometry_rotation_degrees", 0.0))
						var position: Vector2 = packet.get("position", Vector2.ZERO)
						var actual_root := position + Vector2(pivot.x * scale.x, pivot.y * scale.y).rotated(deg_to_rad(rotation))
						var expected_root := LEFT_ROOT if layer_id.contains("left") else RIGHT_ROOT
						root_error_max = maxf(root_error_max, actual_root.distance_to(expected_root))
						var base_scale_y := SOFT_SCALE if is_soft else CORE_SCALE
						var expected_alpha: float = minf(1.0, _phase_base_opacity(phase_name, is_soft) * expected_opacity_factor)
						var clamp_bounds := _scale_y_clamp_bounds(is_soft, phase_name == "start")
						var expected_scale_y := base_scale_y * expected_factor
						if expected_scale_y <= clamp_bounds.x or expected_scale_y >= clamp_bounds.y:
							normal_sweep_clamp_hits += 1
						dynamic_matches = dynamic_matches and absf(scale.y - expected_scale_y) <= 0.0001 \
							and absf(float(packet.get("alpha", 0.0)) - expected_alpha) <= 0.0001
	var lod_matches := true
	for lod_level in ["HIGH", "MEDIUM", "LOW"]:
		var filtered: VfxResult = VfxPreviewLodFilterModel.new().filter(plan_result.value, lod_level, policy_result.value)
		var runtime := _runtime_for(filtered.value, 1.0, 0.0, 0.25) if filtered.success else null
		var expected_bindings := 12 if lod_level == "LOW" else 24
		var expected_renderers := 2 if lod_level == "LOW" else 4
		lod_matches = lod_matches and runtime != null \
			and runtime.active_renderer_count() == expected_renderers \
			and runtime.active_runtime_modulation_binding_count() == expected_bindings \
			and runtime.modulation_sample_count_last_tick() == 1
	tests.expect_true(
		dynamic_matches and root_error_max <= 0.001 and normal_sweep_clamp_hits == 0 and lod_matches,
		"Headlight speed/load/road/ignition mappings preserve all bilateral lamp roots within 0.001 source px across every phase, keep normal-sweep Scale Y values off the safety rails, sample the shared road oscillator once per tick in LOOP, and prune Soft bindings at LOW LOD"
	)


static func _modulation_set_matches(bindings_value: Variant, is_start: bool) -> bool:
	if not bindings_value is Array:
		return false
	var expected: Array[Dictionary] = [
		_expected_mapping("TRANSFORM_SCALE_Y", "RUNTIME_INPUT", "speed_normalized", 0.0, 1.0, 1.0, 1.05),
		_expected_mapping("TRANSFORM_SCALE_Y", "RUNTIME_INPUT", "longitudinal_load", -1.0, 1.0, 0.90, 1.10),
		_expected_mapping("TRANSFORM_SCALE_Y", "PRESET_SOURCE", "road.motion", -1.0, 1.0, 0.99, 1.01),
		_expected_mapping("TRANSFORM_ROTATION_DEGREES", "PRESET_SOURCE", "road.motion", -1.0, 1.0, -0.2, 0.2),
		_expected_mapping("VISUAL_OPACITY_MULTIPLIER", "RUNTIME_INPUT", "speed_normalized", 0.0, 1.0, 1.0, 1.05),
		_expected_mapping("VISUAL_OPACITY_MULTIPLIER", "RUNTIME_INPUT", "longitudinal_load", -1.0, 1.0, 1.12, 0.94)
	]
	if is_start:
		expected.append(_expected_mapping("VISUAL_OPACITY_MULTIPLIER", "PRESET_SOURCE", "start.ignite", 0.0, 1.0, 0.15, 1.0))
		expected.append(_expected_mapping("TRANSFORM_SCALE_Y", "PRESET_SOURCE", "start.ignite", 0.0, 1.0, 0.72, 1.0))
	if bindings_value.size() != expected.size():
		return false
	for expected_binding in expected:
		var found := false
		for binding_value in bindings_value:
			if binding_value is Dictionary and _mapping_matches(binding_value, expected_binding):
				found = true
				break
		if not found:
			return false
	return true


static func _expected_mapping(target: String, source_type: String, source_value: String, input_min: float, input_max: float, output_min: float, output_max: float) -> Dictionary:
	return {
		"target": target,
		"source_type": source_type,
		"source_value": source_value,
		"input_min": input_min,
		"input_max": input_max,
		"output_min": output_min,
		"output_max": output_max
	}


static func _mapping_matches(binding: Dictionary, expected: Dictionary) -> bool:
	var source: Dictionary = binding.get("source", {}) if binding.get("source", {}) is Dictionary else {}
	var mapping: Dictionary = binding.get("mapping", {}) if binding.get("mapping", {}) is Dictionary else {}
	var source_type := str(expected.get("source_type", ""))
	var expected_source_value := str(expected.get("source_value", ""))
	var actual_source_value := str(source.get("input", "")) if source_type == "RUNTIME_INPUT" else str(source.get("source_id", ""))
	return binding.get("target") == expected.get("target") \
		and binding.get("operation") == ("ADD" if binding.get("target") == "TRANSFORM_ROTATION_DEGREES" else "MULTIPLY") \
		and source.get("type") == source_type and actual_source_value == expected_source_value \
		and mapping.get("type") == "LINEAR_RANGE" \
		and is_equal_approx(float(mapping.get("input_min", INF)), float(expected.get("input_min", -INF))) \
		and is_equal_approx(float(mapping.get("input_max", INF)), float(expected.get("input_max", -INF))) \
		and is_equal_approx(float(mapping.get("output_min", INF)), float(expected.get("output_min", -INF))) \
		and is_equal_approx(float(mapping.get("output_max", INF)), float(expected.get("output_max", -INF)))


static func _scale_y_clamp_matches(clamps_value: Variant, is_soft: bool, is_start: bool) -> bool:
	if not clamps_value is Array or clamps_value.size() != 1 or not clamps_value[0] is Dictionary:
		return false
	var clamp: Dictionary = clamps_value[0]
	var expected_bounds := _scale_y_clamp_bounds(is_soft, is_start)
	return clamp.get("target") == "TRANSFORM_SCALE_Y" \
		and absf(float(clamp.get("min_effective", INF)) - expected_bounds.x) <= 0.001 \
		and absf(float(clamp.get("max_effective", INF)) - expected_bounds.y) <= 0.001


# START may dip lower than LOOP/END because the ignition ramp starts the beam at 72% length.
static func _scale_y_clamp_bounds(is_soft: bool, is_start: bool) -> Vector2:
	var base := SOFT_SCALE if is_soft else CORE_SCALE
	return Vector2(base * (0.62 if is_start else 0.89), base * 1.17)


static func _phase_base_opacity(phase_name: String, is_soft: bool) -> float:
	var loop_value: float = LOOP_OPACITY.soft if is_soft else LOOP_OPACITY.core
	return loop_value * (END_OPACITY_RATIO if phase_name == "end" else 1.0)


static func _runtime_for(plan: RefCounted, speed: float, load_value: float, preview_time: float, phase_name := "loop") -> RefCounted:
	if plan == null or plan.runtime_modulation_program() == null:
		return null
	var runtime := VfxPreviewRenderRuntimeModel.new(plan, {"anchors": {"CENTER": [0.0, 0.0]}}, _registry(), VfxPreviewRendererFactoryModel.new(), VfxPreviewAssetResolverModel.new(VfxPreviewAssetRegistryModel.new()))
	var inputs := VfxPreviewRuntimeInputStateModel.new(plan.runtime_modulation_program())
	inputs.set_named_value(plan.runtime_modulation_program(), "speed_normalized", speed)
	inputs.set_named_value(plan.runtime_modulation_program(), "longitudinal_load", load_value)
	runtime.set_runtime_input_state(inputs)
	runtime.activate_phase(phase_name, {"preview_time": preview_time})
	runtime.advance(0.0, {"preview_time": preview_time})
	return runtime


static func _registry() -> RefCounted:
	var registry := VfxSchemaRegistryModel.new(VfxPresetCodecModel.new(), VfxRuleCatalogModel.new())
	registry.load("res://schemas/vfx_schema_v1.json")
	return registry


static func _resolved_assets() -> Dictionary:
	var resolver := VfxPreviewAssetResolverModel.new(VfxPreviewAssetRegistryModel.new())
	var core: VfxResult = resolver.resolve("fx.headlight_beam_core")
	var soft: VfxResult = resolver.resolve("fx.headlight_beam_soft")
	return {"core": core.value if core.success else {}, "soft": soft.value if soft.success else {}}


static func _matches_beam(layer: Dictionary, asset_id: String, importance: String, scale_value: float, rotation: float, opacity: float) -> bool:
	# The wide spill is ALPHA-blended so overlapping cars saturate at the texture colour; the core stays ADDITIVE.
	var expected_blend := "ALPHA" if importance == "DETAIL" else "ADDITIVE"
	var parameters: Dictionary = layer.get("parameters", {}) if layer.get("parameters", {}) is Dictionary else {}
	var transform: Dictionary = layer.get("transform", {}) if layer.get("transform", {}) is Dictionary else {}
	return layer.get("type") == "TEXTURED_SPRITE" \
		and layer.get("importance") == importance and layer.get("blend_mode") == expected_blend and layer.get("render_plane") == "UNDER_VEHICLE" \
		and layer.get("space_mode", "VEHICLE_LOCAL") == "VEHICLE_LOCAL" and layer.get("anchors", ["CENTER"]) == ["CENTER"] \
		and parameters.get("texture_asset_ref") == asset_id and is_equal_approx(float(parameters.get("opacity", -1.0)), opacity) \
		and is_equal_approx(float(transform.get("rotation_degrees", 0.0)), rotation) \
		and _vector_matches(transform.get("scale", []), Vector2(scale_value, scale_value))


# START keeps the LOOP opacity (the ignition ramp is a modulation); END dims the same geometry to a fixed ratio.
static func _phase_uses_loop_geometry(phase_layers: Array, loop: Dictionary, opacity_ratio: float) -> bool:
	for layer in phase_layers:
		if not layer is Dictionary:
			return false
		var phase_id := str(layer.get("id", ""))
		var loop_id := "loop." + phase_id.trim_prefix("start.").trim_prefix("end.")
		var loop_layer: Dictionary = loop.get(loop_id, {})
		var parameters: Dictionary = layer.get("parameters", {}) if layer.get("parameters", {}) is Dictionary else {}
		var expected_opacity: float = float(loop_layer.get("parameters", {}).get("opacity", -1.0)) * opacity_ratio
		if loop_layer.is_empty() or layer.get("type") != "TEXTURED_SPRITE" or layer.get("importance") != loop_layer.get("importance") \
			or layer.get("blend_mode") != loop_layer.get("blend_mode") or layer.get("render_plane") != "UNDER_VEHICLE" \
			or layer.get("anchors", ["CENTER"]) != ["CENTER"] or layer.get("transform") != loop_layer.get("transform") \
			or parameters.get("texture_asset_ref") != loop_layer.get("parameters", {}).get("texture_asset_ref") \
			or not is_equal_approx(float(parameters.get("opacity", -1.0)), expected_opacity):
			return false
	return true


# Where the texture root texel lands in source px for a layer's authored offset/rotation/scale.
static func _beam_root_source(layer: Dictionary, root_texel: Vector2, texture_size: Vector2i) -> Vector2:
	var transform: Dictionary = layer.get("transform", {}) if layer.get("transform", {}) is Dictionary else {}
	var offset := _vector(transform.get("offset", []))
	var scale := _vector(transform.get("scale", []))
	var local := (root_texel - Vector2(texture_size) * 0.5) * scale
	return offset + local.rotated(deg_to_rad(float(transform.get("rotation_degrees", 0.0))))


# Game-pixel width/height of the axis-aligned footprint of a texel rectangle after the layer's scale and rotation.
static func _game_footprint(bounds: Rect2i, layer: Dictionary, track_scale: float) -> Vector2:
	var transform: Dictionary = layer.get("transform", {}) if layer.get("transform", {}) is Dictionary else {}
	var scale := _vector(transform.get("scale", []))
	var radians := deg_to_rad(float(transform.get("rotation_degrees", 0.0)))
	var width := float(bounds.size.x) * scale.x
	var height := float(bounds.size.y) * scale.y
	var cosine := absf(cos(radians))
	var sine := absf(sin(radians))
	return Vector2(cosine * width + sine * height, sine * width + cosine * height) * GAME_SCALE * track_scale


static func _visible_bounds(image: Image, alpha_threshold: float) -> Rect2i:
	if image == null:
		return Rect2i()
	var minimum := Vector2i(image.get_width(), image.get_height())
	var maximum := Vector2i(-1, -1)
	for y in image.get_height():
		for x in image.get_width():
			if image.get_pixel(x, y).a < alpha_threshold:
				continue
			minimum = minimum.min(Vector2i(x, y))
			maximum = maximum.max(Vector2i(x, y))
	return Rect2i(minimum, maximum - minimum + Vector2i.ONE) if maximum.x >= minimum.x and maximum.y >= minimum.y else Rect2i()


# A usable light-cone texture: transparent border, brightest pixel in the expected band (distance from the root in
# texels), axis-centred brightness, and the expected warm (core) or cool (spill) colour at the brightest pixel.
static func _texture_is_clean_light_cone(image: Image, root_texel: Vector2, peak_min: float, peak_max: float, band_min: float, band_max: float, warm: bool) -> bool:
	if image == null:
		return false
	var width := image.get_width()
	var height := image.get_height()
	var border_alpha := 0.0
	var peak := 0.0
	var peak_at := Vector2i.ZERO
	var weighted_x := 0.0
	var weight := 0.0
	for y in height:
		for x in width:
			var alpha := image.get_pixel(x, y).a
			if x == 0 or y == 0 or x == width - 1 or y == height - 1:
				border_alpha = maxf(border_alpha, alpha)
			if alpha > peak:
				peak = alpha
				peak_at = Vector2i(x, y)
			weighted_x += alpha * float(x)
			weight += alpha
	var distance := root_texel.y - float(peak_at.y)
	var centroid_x := weighted_x / maxf(weight, 0.0001)
	var peak_color := image.get_pixel(peak_at.x, peak_at.y)
	var colour_ok := peak_color.r >= peak_color.b if warm else peak_color.b >= peak_color.r
	return border_alpha <= 3.0 / 255.0 and peak >= peak_min and peak <= peak_max \
		and distance >= band_min and distance <= band_max \
		and absf(centroid_x - root_texel.x) <= 1.5 and colour_ok


static func _layers_by_id(layers: Array) -> Dictionary:
	var result := {}
	for layer in layers:
		if layer is Dictionary:
			result[str(layer.get("id", ""))] = layer
	return result


static func _layer_ids(layers: Array) -> Array:
	return layers.map(func(layer: Dictionary) -> String: return str(layer.get("id", "")) if layer is Dictionary else "")


static func _anchor(anchors: Dictionary, name: String) -> Vector2:
	return _vector(anchors.get(name, []))


static func _vector(value: Variant) -> Vector2:
	return Vector2(float(value[0]), float(value[1])) if value is Array and value.size() == 2 else Vector2.INF


static func _vector_matches(value: Variant, expected: Vector2) -> bool:
	var actual := _vector(value)
	return absf(actual.x - expected.x) <= 0.0001 and absf(actual.y - expected.y) <= 0.0001
